general {
        colors = false
        interval = 5
}

order += "volume master"
order += "tztime date"
order += "tztime time"

volume master {
        format = "%volume"
        format_muted = "(%volume)"
        device = "default"
}

tztime date {
        format = "%a %d %b"
}

tztime time {
        format = "%H:%M"
}
