backend = "glx";
vsync = true;
use-damage = true;

fading = false;
fade-in-step = 1;
fade-out-step = 1;
fade-delta = 0;
no-fading-openclose = true;

shadow = false;
blur-background = false;
corner-radius = 0;
